### ISSUE TITLE
Remove by default jenkins plugin on vars file

### ISSUE THREAD

**Issue by jdvr** [idealista/jenkins_role#20]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

The `jenkins_default_plugins` var is on vars file, maybe it shoud be on main.yml to just remove them if you are installing a clean jenkins

### Versions

2.0.1

**Comment by jmonterrubio** [comment]
Nice to hear you JD! XDD
It's intended to have the jenkins_default_plugins in vars file. This is because some of the functionalities of the role needs them. Maybe this list could be created dynamically depending on the functionalities enabled... :)

**Comment by jdvr** [comment]
Fine, I guess it's easier to live with this var to manage a dynamically plugin list generation :smile:
