### ISSUE TITLE
Add support to install Jenkins LTS (2.249.2)

### ISSUE THREAD

**Issue by dortegau** [idealista/jenkins_role#48]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

This role should be able to install Jenkins in its latest version: https://www.jenkins.io/changelog/ (currently v2.263). 

It would be nice if as developer I could choose a specific version of Jenkins, but latest version is installed by default.

**Comment by vicsufer** [comment]
Instead, we'll add support to LTS (2.249.2)
